services:
  postgres:
    image: postgres:16
    container_name: easymoneytracker-postgres
    environment:
      POSTGRES_DB: easymoneytracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - easymoneytracker_postgres_data:/var/lib/postgresql/data

volumes:
  easymoneytracker_postgres_data: